# Generated by Django 5.0.6 on 2024-07-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_listings_comment_bid_item_user_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
